### ISSUE TITLE
Really interesting addon!!!

### ISSUE THREAD

**Issue by subatoiWolf** [Gorgious56/asset_browser_utilities#120]
Does this work with Blender 3.4.1? I seem to be getting this error.   

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\marti\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\asset_browser_utilities-master\__init__.py", line 19, in <module>
    from asset_browser_utilities.core.cache.prop import Cache
ModuleNotFoundError: No module named 'asset_browser_utilities'

**Comment by Gorgious56** [comment]
Hello, please refer to https://github.com/Gorgious56/asset_browser_utilities/issues/35
