### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by Talulaxxx** [Gorgious56/asset_browser_utilities#130]
When activating the addon, the following error appears

Traceback (most recent call last):
  File "D:\Users\Desktop\blender-3.6.5-windows-x64\3.6\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\Usuário\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\asset_browser_utilities-master\__init__.py", line 19, in <module>
    from asset_browser_utilities.core.cache.prop import Cache
ModuleNotFoundError: No module named 'asset_browser_utilities'

I don't understand much about Python, so I don't know how to solve it T-T

**Comment by Gorgious56** [comment]
https://github.com/Gorgious56/asset_browser_utilities/issues/35
