### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by bicukow** [Gorgious56/asset_browser_utilities#131]
Can't install
ERROR:
Traceback (most recent call last):
  File "C:\BLENDER\stable\blender-4.0.2+stable.9be62e85b727\4.0\scripts\modules\addon_utils.py", line 401, in enable
    mod.register()
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\asset_browser_utilities\__init__.py", line 23, in register
    auto_load.init()
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\asset_browser_utilities\auto_load.py", line 29, in init
    modules = get_all_submodules(Path(__file__).parent)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\asset_browser_utilities\auto_load.py", line 60, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\asset_browser_utilities\auto_load.py", line 65, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "C:\BLENDER\stable\blender-4.0.2+stable.9be62e85b727\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\asset_browser_utilities\core\console\command_execute_on_blend_file.py", line 1, in <module>
    from asset_browser_utilities.core.console.command_line_execute_base import CommandLineExecuteBase
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\asset_browser_utilities\core\console\command_line_execute_base.py", line 4, in <module>
    from asset_browser_utilities.core.cache.tool import get_current_operator_properties
ImportError: cannot import name 'get_current_operator_properties' from 'asset_browser_utilities.core.cache.tool' (C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\asset_browser_utilities\core\cache\tool.py)

**Comment by Flowgun** [comment]
When you download the ZIP, GitHub automatically adds "- master" suffix to the zipped folder. 
you need to go to your addons folder and remove that suffix so you can activate the addon.

**Comment by Gorgious56** [comment]
thanks @Flowgun 
See https://github.com/Gorgious56/asset_browser_utilities/issues/35
