### ISSUE TITLE
4.1.1 not working 

### ISSUE THREAD

**Issue by cid-wings** [Gorgious56/asset_browser_utilities#142]
Hi not working at all got this error when I install it 

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\USER_NAME\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\asset_browser_utilities-master\__init__.py", line 19, in <module>
    from asset_browser_utilities.core.cache.prop import Cache
ModuleNotFoundError: No module named 'asset_browser_utilities'

**Comment by Gorgious56** [comment]
Hello please check https://github.com/Gorgious56/asset_browser_utilities/issues/35
