### ISSUE TITLE
Error installing Blender 3.2

### ISSUE THREAD

**Issue by SevenMSchultze** [Gorgious56/asset_browser_utilities#75]
Blender 3.2 stable

We Use the portable/mobile version of Blender stored an another Network Drive, not locally on every machine

I get this Error Message, when trying to install the addon. 

Exception in module register(): C:\Users\andreas\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\asset_browser_utilities-master\__init__.py
Traceback (most recent call last):
  File "N:\Blender\Release\WORK_BUILD\3.2\scripts\modules\addon_utils.py", line 371, in enable
    mod.register()
  File "C:\Users\andreas\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\asset_browser_utilities-master\__init__.py", line 22, in register
    auto_load.init()
  File "C:\Users\andreas\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\asset_browser_utilities-master\auto_load.py", line 29, in init
    modules = get_all_submodules(Path(__file__).parent)
  File "C:\Users\andreas\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\asset_browser_utilities-master\auto_load.py", line 60, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
  File "C:\Users\andreas\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\asset_browser_utilities-master\auto_load.py", line 65, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "N:\Blender\Release\WORK_BUILD\3.2\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\andreas\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\asset_browser_utilities-master\core\cache\prop.py", line 1, in <module>
    from asset_browser_utilities.module.author.set import AuthorSetOperatorProperties
ModuleNotFoundError: No module named 'asset_browser_utilities'

**Comment by SevenMSchultze** [comment]
So I've now seen the Isssue #35 . Should work now!

**Comment by Gorgious56** [comment]
Yup same issue ! I recommend you use the latest release instead of the mirror from github. Did you manage to make it work ?

**Comment by SevenMSchultze** [comment]
> Yup same issue ! I recommend you use the latest release instead of the mirror from github. Did you manage to make it work ?

Yes. Thanks for your help. It works fine and is really a time saver. Thank you for providing such a useful tool!

**Comment by Gorgious56** [comment]
Glad it worked ! I'll close the issue if you don't mind so it doesn't fill up the backlog :)

Don't hesitate to post any feedback here or on the blenderartsists thread.
Cheers !
